# Generated by Django 6.0.1 on 2026-02-05 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='adjunto',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curso',
            name='profesor',
            field=models.CharField(default=' ', max_length=50),
            preserve_default=False,
        ),
    ]
